//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 12:19:48 PM GMT 
//


package com.telrock.tsys_accounts.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for messageTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="messageTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SMS"/&gt;
 *     &lt;enumeration value="EMAIL"/&gt;
 *     &lt;enumeration value="PUSH"/&gt;
 *     &lt;enumeration value="VOICE"/&gt;
 *     &lt;enumeration value="SOCIAL_MEDIA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "messageTypeEnum")
@XmlEnum
public enum MessageTypeEnum {

    SMS,
    EMAIL,
    PUSH,
    VOICE,
    SOCIAL_MEDIA;

    public String value() {
        return name();
    }

    public static MessageTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
