//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.06 at 12:19:48 PM GMT 
//

package com.telrock.tsys_accounts.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for sendMessageText complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sendMessageText"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="senderId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="recipient" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="messageText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="properties" type="{http://soap.tsys_accounts.telrock.com/}messageProperties" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendMessageText", propOrder = { "senderId", "recipient", "messageText", "accountId", "properties" })
public class SendMessageText
{

	@XmlElement(required = true)
	protected String senderId;
	@XmlElement(required = true)
	protected String recipient;
	@XmlElement(required = true)
	protected String messageText;
	protected String accountId;
	protected MessageProperties properties;

	@Override
	public String toString()
	{
		StringBuilder builder = new StringBuilder();
		builder.append("SendMessageText [senderId=");
		builder.append(senderId);
		builder.append(", recipient=");
		builder.append(recipient);
		builder.append(", messageText=");
		builder.append(messageText);
		builder.append(", accountId=");
		builder.append(accountId);
		builder.append(", properties=");
		builder.append(properties);
		builder.append("]");
		return builder.toString();
	}

	/**
	 * Gets the value of the senderId property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSenderId()
	{
		return senderId;
	}

	/**
	 * Sets the value of the senderId property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setSenderId(String value)
	{
		this.senderId = value;
	}

	/**
	 * Gets the value of the recipient property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRecipient()
	{
		return recipient;
	}

	/**
	 * Sets the value of the recipient property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setRecipient(String value)
	{
		this.recipient = value;
	}

	/**
	 * Gets the value of the messageText property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMessageText()
	{
		return messageText;
	}

	/**
	 * Sets the value of the messageText property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setMessageText(String value)
	{
		this.messageText = value;
	}

	/**
	 * Gets the value of the accountId property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAccountId()
	{
		return accountId;
	}

	/**
	 * Sets the value of the accountId property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 */
	public void setAccountId(String value)
	{
		this.accountId = value;
	}

	/**
	 * Gets the value of the properties property.
	 * 
	 * @return possible object is {@link MessageProperties }
	 */
	public MessageProperties getProperties()
	{
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 * 
	 * @param value
	 *           allowed object is {@link MessageProperties }
	 */
	public void setProperties(MessageProperties value)
	{
		this.properties = value;
	}

}
