version: '2'

services:
  consul:
    image: progrium/consul
    command: -server -bootstrap -advertise 10.0.2.15
    networks:
      - discovery
          
  registrator:
    image: gliderlabs/registrator
    command: consul://consul:8500
    depends_on:
      - consul
    networks:
      - discovery
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    
  web:
    build:
      context: ./httpd
    image: mattdiggins/web
    depends_on:
      - consul
      - registrator
    ports:
     - "80:80"
    environment:
       SERVICE_80_NAME: http
       SERVICE_NAME: apache
       SERVICE_TAGS: web
    networks:
      - web
      - discovery
      - app
      
  
      
networks:
   web:
     driver: bridge
   discovery:
     driver: bridge
   app:
     driver: bridge
      